;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        electric-newline-and-maybe-indent
        indent-for-tab-command
        keyboard-escape-quit
        kill-region
        markdown-outdent-or-delete
        org-beginning-of-line
        org-kill-line
        org-promote-subtree
        org-self-insert-command
        sgml-slash
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        consult-buffer
        consult-yank-pop
        end-of-buffer
        mouse-set-region
        org-cycle
        org-end-of-line
        undo-redo
        xref-find-definitions
        ))
