;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        electric-newline-and-maybe-indent
        indent-for-tab-command
        markdown-outdent-or-delete
        org-self-insert-command
        sgml-slash
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        consult-buffer
        consult-yank-pop
        end-of-buffer
        mouse-set-region
        xref-find-definitions
        ))
